version: 0.0
os: linux
files:
  - source: /
    destination: /home/ec2-user/aqueduct
hooks:
  BeforeInstall:
    - location: scripts/before_install.sh
  AfterInstall:
    - location: scripts/install.sh
      runas: ec2-user
  ApplicationStart:
    - location: scripts/restart_app.sh
      timeout: 3600
      runas: ec2-user
